apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-nginx-hpa # Navnet på vores HPA
spec:
  scaleTargetRef: # Hvilket deployment skal skaleres?
    apiVersion: apps/v1
    kind: Deployment
    name: my-nginx-app
  minReplicas: 2   # Minimum antal pods (det vi starter med)
  maxReplicas: 10  # Maksimum antal pods, vi vil skalere op til
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Mål: Hold CPU-forbruget på 50%